# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:#073642)\
$os\
$username\
[ ](fg:#073642 bg:#1c4961)\
$directory\
[ ](fg:#1C4961 bg:#2F79A1)\
$git_branch\
[ ](fg:#2F79A1 bg:#3A95C7)\
$git_status\
[](fg:#3a95c7)\
$fill\
$golang\
$python\
$rust\
$lua\
$nim\
$rust\
$zig\
$line_break\
$character """


add_newline = true


palette ='zolarized_dark'

[palettes.zolarized_dark]
base03 = '#002b36' # dark BG
base02 = '#073642' # lighter BG
base01 = '#586e75' # content, light grey
base00 = '#657b83'
base0 = '#839496'
base1 = '#93a1a1'
yellow = '#b58900'
brred = '#cb4b16'
red = '#dc322f'
magenta = '#d33682'
violet = '#6c71c4'
blue = '#268bd2'
cyan = '#2aa198'
green = '#859900'

[fill]
symbol = ' '
# style = 'base00'

[os]
disabled = false
style = "bg:#073642 fg:base1"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:#073642 fg:green"
style_root = "bg:#1c4961 fg:red"
format = '[ $user ]($style)'

[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
style = "bg:#1C4961"

[git_branch]
symbol = ""
format = "[ $symbol $branch ]($style)"
style = "bg:#2F79A1 fg:white"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "bg:#3A95C7 fg:white"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[rust]
symbol = ""
style = "bg:brred"
format = '[[ $symbol( $version) ](fg:#cb4b16 fg:white)]($style)'

[golang]
symbol = ""
style = "fg:cyan bg:base02"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:green fg:#073642"
format = "[ $time ]($style)"
